strictness: veryhigh

pylint:
  disable:
    - unused-argument
    - too-few-public-methods
    - too-many-arguments
    - not-a-mapping
    - unnecessary-lambda
    - unsubscriptable-object  # https://github.com/PyCQA/pylint/issues/3882
