name: Validate
on: push

jobs:
  runner-job:
    runs-on: python:3.8

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Lint
        run: poetry run prospector

      - name: Test
        run: poetry run pytest
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres:5432/test
